[Qt]
style=breeze

[StandardPaths]
AppConfigLocation=%APPDATA%/Gpg4win/::APPNAME::
AppDataLocation=%APPDATA%/Gpg4win/::APPNAME::
AppLocalDataLocation=%LOCALAPPDATA%/Gpg4win/::APPNAME::
CacheLocation=%LOCALAPPDATA%/Gpg4win/::APPNAME::/cache
ConfigLocation=%APPDATA%/Gpg4win/::APPNAME::
StateLocation=%LOCALAPPDATA%/Gpg4win/::APPNAME::/State
GenericCacheLocation=%LOCALAPPDATA%/Gpg4win/cache
GenericConfigLocation=%APPDATA%/Gpg4win
GenericDataLocation=%LOCALAPPDATA%/Gpg4win
GenericStateLocation=%LOCALAPPDATA%/Gpg4win/State
